import { InMemoryDbService } from "angular-in-memory-web-api";
import { Category } from "./pages/categories/shared/category.model";
import { EntryModel } from "./pages/entries/shared/entry.model";

export class InMemoryDatabase implements InMemoryDbService {
  createDb() {
    const categories: Category[] = [
      { id: 1, name: "Moradia", description: "Pagamentos das contas da casa" },
      { id: 2, name: "Saúde", description: "Plano de saúde e remédios" },
      { id: 3, name: "Lazer", description: "Cinema, parques, praia, etc" },
      { id: 4, name: "Salários", description: "Recebimento de salário" },
      { id: 5, name: "Freelas", description: "Trabalhos com freelances" },
    ];

    const entries: EntryModel[] = [
      {
        id: 1,
        name: "Gás de Cozinha",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/10/2018",
        amount: "70,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 2,
        name: "Luz",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "14/10/2018",
        amount: "100",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 3,
        name: "Água",
        categoryId: categories[2].id,
        category: categories[2],
        paid: true,
        date: "14/10/2018",
        amount: "200,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 4,
        name: "Aluguel",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/10/2018",
        amount: "1070,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 5,
        name: "Condominio",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/10/2018",
        amount: "700,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 6,
        name: "NET",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/10/2018",
        amount: "750,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 7,
        name: "Salario",
        categoryId: categories[3].id,
        category: categories[3],
        paid: true,
        date: "12/10/2018",
        amount: "10000",
        type: "revenue",
        description: "Money",
      } as EntryModel,
      {
        id: 8,
        name: "Gás de Cozinha",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/06/2020",
        amount: "50,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 9,
        name: "Luz",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/06/2020",
        amount: "90",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 10,
        name: "Água",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/06/2020",
        amount: "100,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 11,
        name: "Aluguel",
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: "14/06/2020",
        amount: "1070,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 12,
        name: "Condominio",
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: "14/06/2020",
        amount: "700,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 13,
        name: "NET",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "14/06/2020",
        amount: "730,80",
        type: "expense",
        description: "Qaulquer coisa",
      } as EntryModel,
      {
        id: 14,
        name: "Salario",
        categoryId: categories[3].id,
        category: categories[3],
        paid: true,
        date: "12/06/2020",
        amount: "10000",
        type: "revenue",
        description: "Money",
      } as EntryModel,
    ];

    return { categories, entries };
  }
}
